const fs = require('fs');

let text = fs.readFileSync('public/app.js', 'utf8');

const replacements = {
  "zamÄ‚Ĺ‚wieÄąâ€ž": "zamówień",
  "ZamÄ‚Ĺ‚wieÄąâ€ž": "Zamówień",
  "zamÄ‚Ĺ‚wienie": "zamówienie",
  "ZamÄ‚Ĺ‚wienie": "Zamówienie",
  "zamÄ‚Ĺ‚wienia": "zamówienia",
  "ZamÄ‚Ĺ‚wienia": "Zamówienia",
  "zamÄ‚Ĺ‚wiÄ‚â€žÄąâ€š": "zamówił",
  "ZamÄ‚Ĺ‚wiÄ‚â€žÄąâ€š": "Zamówił",
  "NieopÄąâ€šacone": "Nieopłacone",
  "nieopÄąâ€šacone": "nieopłacone",
  "OpÄąâ€šacone": "Opłacone",
  "opÄąâ€šacone": "opłacone",
  "materiaÄąâ€šy": "materiały",
  "MateriaÄąâ€šy": "Materiały",
  "materiaÄąâ€šĂ‚Ĺ‚w": "materiałów",
  "MateriaÄąâ€šĂ‚Ĺ‚w": "Materiałów",
  "wycenÄ‚â€žÄ…": "wyceną",
  "WycenÄ‚â€žÄ…": "Wyceną",
  "wycenÄ‚â€žÄ…": "wycenę",
  "WycenÄ‚â€žÄ…": "Wycenę",
  "zamkniÄ‚â€žÄ…te": "zamknięte",
  "ZamkniÄ‚â€žÄ…te": "Zamknięte",
  "pÄąâ€šatnoÄąâ€şci": "płatności",
  "PÄąâ€šatnoÄąâ€şci": "Płatności",
  "zÄąâ€š": "zł",
  "ZÄąâ€š": "Zł",
  "UsunÄ‚â€žÄ…Ä‚â€žÄ…Ä‚â€žÄ…": "Usunąć",
  "usunÄ‚â€žÄ…Ä‚â€žÄ…Ä‚â€žÄ…": "usunąć",
  "powiÄ‚â€žÄ…zane": "powiązane",
  "PowiÄ‚â€žÄ…zane": "Powiązane",
  "caÄąâ€šy": "cały",
  "CaÄąâ€šy": "Cały",
  "wpÄąâ€šaty": "wpłaty",
  "WpÄąâ€šaty": "Wpłaty",
  "pozycjÄ‚â€žÄ…": "pozycję",
  "PozycjÄ‚â€žÄ…": "Pozycję",
  "usuniÄ‚â€žÄ…cia": "usunięcia",
  "usuniÄ‚â€žÄ…te": "usunięte",
  "UsuniÄ‚â€žÄ…to": "Usunięto",
  "poniÄ‚ĹĽej": "poniżej",
  "bÄ‚â€šÄ‚â€žÄ…d": "błąd",
  "BÄ‚â€šÄ‚â€žÄ…d": "Błąd",
  "zgÄąâ€šoszenia": "zgłoszenia",
  "ZgÄąâ€šoszenia": "Zgłoszenia",
  "OdÄąâ€şwieÄ‚ĹĽ": "Odśwież",
  "odÄąâ€şwieÄ‚ĹĽ": "odśwież",
  "policzyÄ‚â€žÄ…Ä‚â€žÄ…": "policzyć",
  "wedÄąâ€šug": "według",
  "szczegÄ‚Ĺ‚Äąâ€šy": "szczegóły",
  "SzczegÄ‚Ĺ‚Äąâ€šy": "Szczegóły",

  // Let's add variations from `app.js` grep output
  "zam''wie?": "zamówień",
  "zam''wienie": "zamówienie",
  "Zam''wienie": "Zamówienie",
  "zam''wienia": "zamówienia",
  "Zam''wienia": "Zamówienia",
  "zam''wi\"?": "zamówił",
  "Nieop?acone": "Nieopłacone",
  "nieop?acone": "nieopłacone",
  "Op?acone": "Opłacone",
  "op?acone": "opłacone",
  "materia?y": "materiały",
  "Materia?y": "Materiały",
  "materia?''w": "materiałów",
  "wycen\"\"": "wycenę",
  "zamkni\"\"te": "zamknięte",
  "Zamkni\"\"te": "Zamknięte",
  "p?atno?ci": "płatności",
  "P?atno?ci": "Płatności",
  "z?": "zł",
  "Z?": "Zł",
  "Usun\"?|\"?": "usunąć",
  "powi\"?|zane": "powiązane",
  "Powi\"?|zane": "Powiązane",
  "ca?y": "cały",
  "Ca?y": "Cały",
  "wp?aty": "wpłaty",
  "Wp?aty": "Wpłaty",
  "pozycj\"\"": "pozycję",
  "Pozycj\"\"": "Pozycję",
  "usuni\"\"cia": "usunięcia",
  "usuni\"\"te": "usunięte",
  "Usuni\"\"to": "Usunięto",
  "poniej": "poniżej",
  "b\"?|d": "błąd",
  "B\"?|d": "Błąd",
  "zg?oszenia": "zgłoszenia",
  "Zg?oszenia": "Zgłoszenia",
  "Od?wie": "Odśwież",
  "od?wie": "odśwież",
  "policzy\"?": "policzyć",
  "wed?ug": "według",
  "szczeg''?y": "szczegóły",
  "Szczeg''?y": "Szczegóły",

  "zamÄ‚Ĺ‚wieĂ„â€ž": "zamówień",
  "zamĂłwieĹ„": "zamówień",
  "ZamĂłwieĹ„": "Zamówień",
  "zamĂłwienie": "zamówienie",
  "ZamĂłwienie": "Zamówienie",
  "zamĂłwienia": "zamówienia",
  "ZamĂłwienia": "Zamówienia",
  "NieopĹ‚acone": "Nieopłacone",
  "OpĹ‚acone": "Opłacone",
  "materiaĹ‚y": "materiały",
  "materiałĂłw": "materiałów",
  "wycenÄ™": "wycenę",
  "zamkniÄ™te": "zamknięte",
  "pĹ‚atnoĹ›ci": "płatności",
  "zĹ‚": "zł",
  "UsunÄ…Ä‡": "usunąć",
  "powiÄ…zane": "powiązane",
  "caĹ‚y": "cały",
  "wpĹ‚aty": "wpłaty",
  "pozycjÄ™": "pozycję",
  "usuniÄ™cia": "usunięcia",
  "usuniÄ™te": "usunięte",
  "UsuniÄ™to": "Usunięto",
  "poniĹĽej": "poniżej",
  "bĹ‚Ä…d": "błąd",
  "zgĹ‚oszenia": "zgłoszenia",
  "OdĹ›wieĹĽ": "Odśwież",
  "policzyÄ‡": "policzyć",
  "wedĹ‚ug": "według",
  "szczegĂłĹ‚y": "szczegóły"
};

for (const [bad, good] of Object.entries(replacements)) {
  text = text.replaceAll(bad, good);
}

fs.writeFileSync('public/app.js', text, 'utf8');
console.log('Fixed using mapping!');
